/* Question:
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
Example 3:

Input: s = "a", t = "aa"
Output: "a"
Example 4:

Input: s = "ae", t = "aea"
Output: "a"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lower-case English letters.   */

//Solution 1
class Solution {
    public char findTheDifference(String s, String t) {
		int sumS = 0, sumT = 0;
		char[] arrS = s.toCharArray();
		char[] arrT = t.toCharArray();
		for (int i = 0; i < arrS.length; i++) {
			sumS += arrS[i] - 'a';
			sumT += arrT[i] - 'a';
		}
		sumT += arrT[arrT.length - 1] - 'a';
		return (char) (sumT - sumS + 'a');
	}
}

//Solution 2
class Solution {
    public char findTheDifference(String s, String t) {
        int[] s_freq=new int[26];
        int[] t_freq=new int[26];
        char ans='a';
        for(char c:s.toCharArray()){
            s_freq[c-'a']++;
        }
        for(char c:t.toCharArray()){
            t_freq[c-'a']++;
        }
        for(int i=0;i<26;i++){
            if(t_freq[i]>s_freq[i])
                return ((char)(i+'a'));
        }
        return ans;
    }
}
